# Generated by Django 5.0.7 on 2024-09-01 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificate', '0003_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.area'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.course'),
        ),
        migrations.AddField(
            model_name='homework',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.course'),
        ),
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='areas',
            field=models.ManyToManyField(blank=True, to='organization.area'),
        ),
        migrations.AddField(
            model_name='organization',
            name='certificates',
            field=models.ManyToManyField(blank=True, related_name='organization_certificates', to='certificate.certificate'),
        ),
        migrations.AddField(
            model_name='organization',
            name='courses',
            field=models.ManyToManyField(blank=True, to='organization.course'),
        ),
        migrations.AddField(
            model_name='organization',
            name='moderator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_organization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_organization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teacher_organization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.area'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(to='organization.question'),
        ),
        migrations.AddField(
            model_name='organization',
            name='quizes',
            field=models.ManyToManyField(blank=True, related_name='organization_quizzes', to='organization.quiz'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.quiz'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='organization.room'),
        ),
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.room'),
        ),
        migrations.AddField(
            model_name='course',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='course_themes', to='organization.theme'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='organization.variant'),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='question_options', to='organization.variant'),
        ),
    ]
