# Generated by Django 5.0.7 on 2024-09-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.CharField(choices=[('05:00', '05:00'), ('10:00', '10:00'), ('15:00', '15:00'), ('20:00', '20:00'), ('25:00', '25:00'), ('30:00', '30:00'), ('35:00', '35:00'), ('40:00', '40:00'), ('45:00', '45:00')], max_length=10),
        ),
    ]
