# Generated by Django 5.0.7 on 2024-09-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_quiz_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='name',
            new_name='title',
        ),
    ]
