# Generated by Django 5.0.7 on 2024-09-11 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_rename_name_quiz_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.CharField(default='Yangi mavzu', max_length=250),
        ),
    ]
