# Generated by Django 5.0.7 on 2024-09-11 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organization_create_at_alter_theme_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
